# Generated by Django 5.1.7 on 2025-03-17 01:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_cartitem_price_at_time_order_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price_at_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
