# Generated by Django 5.1.7 on 2025-03-17 01:48

from django.db import migrations
from decimal import Decimal

def update_cart_item_prices(apps, schema_editor):
    CartItem = apps.get_model('shop', 'CartItem')
    for item in CartItem.objects.all():
        if not item.price_at_time:
            item.price_at_time = item.product.base_price
            item.save()

def reverse_cart_item_prices(apps, schema_editor):
    CartItem = apps.get_model('shop', 'CartItem')
    CartItem.objects.all().update(price_at_time=None)

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_cartitem_price_at_time_delete_offer'),
    ]

    operations = [
        migrations.RunPython(
            update_cart_item_prices,
            reverse_cart_item_prices
        ),
    ]
